# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logEntry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='logEntry.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=_b('\n\"com.konux.interview.assignment.dtoB\rLogEntryProto'),
  serialized_pb=_b('\n\x0elogEntry.proto\x12\x08tutorial\"<\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\x0e\n\x06userId\x18\x02 \x02(\x03\x12\r\n\x05\x65vent\x18\x03 \x02(\tB3\n\"com.konux.interview.assignment.dtoB\rLogEntryProto')
)




_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='tutorial.LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='tutorial.LogEntry.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='tutorial.LogEntry.userId', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='tutorial.LogEntry.event', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), dict(
  DESCRIPTOR = _LOGENTRY,
  __module__ = 'logEntry_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.LogEntry)
  ))
_sym_db.RegisterMessage(LogEntry)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
